# _config.yml
title: "abc"
description: "abc"
url: "https://jax-169.github.io"   # 顶级域名
baseurl: "/k"                         # 子路径仓库改为 "/仓库名"
lang: zh-CN
theme: jekyll-theme-chirpy          # 关键：声明主题

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 更多配置参考：https://github.com/cotes2020/chirpy-starter/blob/main/_config.yml
