# 核心配置
name: "你的博客名称"
url: "https://jax-169.github.io"   # 不要带/k路径
baseurl: "/k"  # 关键配置项，必须带斜杠前缀
lang: zh-CN
timezone: Asia/Shanghai

# 主题支持
theme: jekyll-theme-chirpy

# 资源路径配置 (必须使用baseurl)
assets:
  image: "{{ site.baseurl }}/assets/img"

# 示例图片引用（在文章中这样使用）
# ![描述]({{ site.assets.image }}/avatar.jpg)
