# _config.yml
title: "123"
tagline: "123"
description: "123"
url: "https://jax-169.github.io/k"  # 必须匹配仓库路径
lang: zh-CN
timezone: Asia/Shanghai
avatar: /Image_1749045037439.jpg  # 需上传图片到 /assets/img/

# 主题配置
theme_mode:
  light: solarized  # 浅色模式样式
  dark: dark  # 深色模式样式

# 社交链接
social:
  name: "abc"
  email: "q_398@foxmail.com"
  links:
    github: https://github.com/jax-169
    

# Giscus 评论系统
comments:
  provider: giscus
  giscus:
    repo: 你的用户名/k  # 仓库名
    category: Announcements

# 插件
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
